defaults: &defaults
  :log_level: warn
  :roles:
    :admin:
      - pivotaltracker@bidsync.com
      - bjn@bidsync.com
    :user:
  :active_record:
      :adapter: sqlite3
      :database: "db/sqlite/pivot.db"

:development:
  <<: *defaults
  :log_level: debug

:test:
  <<: *defaults

:production:
  <<: *defaults
  :active_record:
    :adapter: sqlite3
    :database: "../../shared/db/sqlite/pivot.db"
